allOf:
  - type: object
    properties:
      _id:
        type: string
        format: uuid
        description: project id.
      ownerId:
        type: string
        format: uuid
        description: project owner id.
      accessUsers:
        type: array
        description: access users information.
  - $ref: "/schema/shared/projectInput.yaml"
  - $ref: "/schema/shared/time.yaml"
