openapi: 3.1.0
info:
  title: DINO Redoc
  description: |
    # enums description

    ## app abbreviation
    - "fa": family album
    - "mt": money tracker

    ## access level
    - "0": none
    - "1": viewer
    - "2": commentor
    - "5": editor
    - "9": admin
    - "10": super admin
servers:
  - url: http://localhost:3000/api
tags:
  - name: user
  - name: project
  - name: s3
  - name: album
  - name: transaction
  - name: budget
schemes:
  - https
  - http
x-tagGroups:
  - name: core
    tags:
      - user
      - project
      - s3
  - name: family album
    tags:
      - album
  - name: money tracker
    tags:
      - transaction
      - budget
paths:
  /auth/me:
    $ref: "/path/user/me.yaml"
  /app/{appAbbreviation}/admin/user:
    $ref: "/path/user/user.yaml"
  /app/{appAbbreviation}/admin/user/{userId}:
    $ref: "/path/user/userTarget.yaml"
  /app/{appAbbreviation}/project:
    $ref: "/path/project/project.yaml"
  /app/{appAbbreviation}/project/{projectId}:
    $ref: "/path/project/projectTarget.yaml"
  /s3/pre_signed_download:
    $ref: "/path/s3/preSignedDownload.yaml"
  /s3/pre_signed_upload:
    $ref: "/path/s3/preSignedUpload.yaml"
  /app/fa/album/post:
    $ref: "/path/album/post.yaml"
  /app/fa/album/asset/{assetId}:
    $ref: "/path/album/assetTarget.yaml"
  /app/fa/album/comment:
    $ref: "/path/album/comment.yaml"
  /app/fa/album/category:
    $ref: "/path/album/category.yaml"
  /app/fa/album/category/{categoryId}:
    $ref: "/path/album/categoryTarget.yaml"
components:
  enums:
    appAbbreviation:
      type: string
      enum:
        - fa
        - mt
    accessLevel:
      type: string
      enum:
        - "0"
        - "1"
        - "2"
        - "5"
        - "9"
        - "10"
