openapi: 3.0.3
info:
  title: DINO Redoc
  description: |
    # enums description

    ## app abbreviation
    - "fa": family album
    - "mt": money tracker

    ## access level
    - "0": none
    - "1": viewer
    - "2": commentor
    - "5": editor
    - "9": admin
    - "10": super admin
servers:
  - url: http://localhost:3000/api
tags:
  - name: user
  - name: project
  - name: s3
  - name: album
  - name: transaction
  - name: budget
schemes:
  - https
  - http
x-tagGroups:
  - name: core
    tags:
      - user
      - project
      - s3
  - name: family album
    tags:
      - album
  - name: money tracker
    tags:
      - transaction
      - budget
paths:
  /auth/me:
    get:
      tags:
        - user
      summary: get current user
      description: get current user information.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "/schema/shared/user.yaml"
        400:
          description: unexpected error
        405:
          description: invalid method
  /app/{appAbbreviation}/admin/user:
    get:
      tags:
        - user
      summary: get user lists
      description: get user lists to change user's permission. only admin or super admin user can get the lists.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "/parameter/shared/appAbbreviation.yaml"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "/schema/shared/user.yaml"
        400:
          description: unexpected error
        401:
          description: unauthorized
        405:
          description: invalid method
  /app/{appAbbreviation}/admin/user/{userId}:
    put:
      tags:
        - user
      summary: update user permission
      description: update user's permission. only admin or super admin user can update the permission.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "/parameter/shared/appAbbreviation.yaml"
        - name: userId
          description: target user id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "/schema/shared/user.yaml"
        400:
          description: unexpected error
        401:
          description: unauthorized
        405:
          description: invalid method
components:
  enums:
    appAbbreviation:
      type: string
      enum:
      - fa
      - mt
    accessLevel:
      type: string
      enum:
      - "0"
      - "1"
      - "2"
      - "5"
      - "9"
      - "10"
