openapi: 3.1.0
info:
  title: DINO Redoc
  description: |
    # enums description

    ## album collection
    - "album.posts": post colleciton name
    - "album.assets": asset collection name
    - "album.categories": category collection name
    - "album.reactions": reaction collection name
    - "album.comments": comment collection name

    ## app abbreviation
    - "fa": family album
    - "mt": money tracker

    ## access level
    - "0": none
    - "1": viewer
    - "2": commentor
    - "5": editor
    - "9": admin
    - "10": super admin

    ## reaction
    - "LIKE": LIKE,
    - "LOVE": LOVE,
    - "HAHA": HAHA,
    - "WOW": WOW,
    - "SAD": SAD,
    - "ANGRY": ANGRY

    ## postAudience
    - "ALL": ALL,
    - "VIEWER": VIEWER,
servers:
  - url: http://localhost:3000/api
tags:
  - name: user
  - name: project
  - name: s3
  - name: album
  - name: transaction
  - name: budget
schemes:
  - https
  - http
x-tagGroups:
  - name: core
    tags:
      - user
      - project
      - s3
  - name: family album
    tags:
      - album
  - name: money tracker
    tags:
      - transaction
      - budget
paths:
  /auth/me:
    $ref: "/path/user/me.yaml"
  /app/{appAbbreviation}/admin/user:
    $ref: "/path/user/user.yaml"
  /app/{appAbbreviation}/admin/user/{userId}:
    $ref: "/path/user/userTarget.yaml"
  /app/{appAbbreviation}/project:
    $ref: "/path/project/project.yaml"
  /app/{appAbbreviation}/project/{projectId}:
    $ref: "/path/project/projectTarget.yaml"
  /s3/pre-signed-download:
    $ref: "/path/s3/preSignedDownload.yaml"
  /s3/pre-signed-upload:
    $ref: "/path/s3/preSignedUpload.yaml"
  /s3/delete-s3-objects:
    $ref: "/path/s3/deleteS3Objects.yaml"
  /app/fa/album/post:
    $ref: "/path/album/post.yaml"
  /app/fa/album/post/${postId}:
    $ref: "/path/album/postTarget.yaml"
  /app/fa/album/asset/{assetId}:
    $ref: "/path/album/assetTarget.yaml"
  /app/fa/album/comment:
    $ref: "/path/album/comment.yaml"
  /app/fa/album/comment/{commentId}:
    $ref: "/path/album/commentTarget.yaml"
  /app/fa/album/reaction:
    $ref: "/path/album/reaction.yaml"
  /app/fa/album/reaction/{reactionId}:
    $ref: "/path/album/reactionTarget.yaml"
  /app/fa/album/category:
    $ref: "/path/album/category.yaml"
  /app/fa/album/category/{categoryId}:
    $ref: "/path/album/categoryTarget.yaml"
components:
  enums:
    appAbbreviation:
      type: string
      enum:
        - fa
        - mt
    accessLevel:
      type: string
      enum:
        - "0"
        - "1"
        - "2"
        - "5"
        - "9"
        - "10"
    reaction:
      type: string
      enum:
        - LIKE
        - LOVE
        - HAHA
        - WOW
        - SAD
        - ANGRY
    postAudience:
      type: string
      enum:
        - ALL
        - VIEWER
